/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arraytest3;

public class App {
    public static void main(String[] args) {
        /* 1차원 배열의 생성 */
        int anArray1[] = new int[5];
        int[] anAray2 = new int[] {1, 2, 3, 4, 5};
        int anArray3[];
        anArray3 = new int[5];
        anArray3[0] = 1;
        anArray3[1] = 2;
        anArray3[2] = 3;
        anArray3[3] = 4;
        anArray3[4] = 5;
    }
}
