/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arraytest2;

public class App {
    public static void main(String[] args) {
        /* 1차원 배열의 초기화 */
        int anArray1[] = {1, 2, 3, 4, 5};
        int[] anAray2 = {1, 2, 3, 4, 5};
        /* 2차열 배열의 초기화 */
        int anArray3[][] = {{1, 2, 3}, {4, 5, 6}};
        int[][] anArray4 = {{1, 2, 3}, {4, 5, 6}};

        int anArray5[];
    }
}
