/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arraytest1;

public class App {
    public static void main(String args[]) {
        /* 1차원 배열 선언 */
        int anArray1[];
        int[] anArray2;
        /* 2차원 배열 선언 */
        int anArray3[][];
        int[][] anArray4;
        int[] anArray6[];
    }
}
