/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arraytest4;

public class App {
    public static void main(String[] args) {
        int anArray1[] = new int[5];
        for (int i = 0; i < anArray1.length; i++) {
            anArray1[i] = i;
        }
        int anAray2[][] = new int[2][3];
        for(int i = 0; i < anAray2.length; i++) {
            for(int j = 0; j < anAray2[i].length; j++) {
                anAray2[i][j] = i;
            }
        }
    }
}
